Consensus clustering
epigenelabs/inmoose pull request #7
Opened 2023-08-04 14:52 UTC by soleneweill

## What ?
Python implementation of consensus clustering related to the issue #5 

## Next
Add cophenetic correlation and silouhette analysis to select the best number of cluster automatically
Test code with other algorithms than hierarchical clustering

2023-08-07 13:22 UTC, guillaumeap reviewed
Very nice work, I have still a few comments
Also, is it wanted in `compute_summary_statistics` to be able to precise any K? Do we want to be able to compute them for another K than bestK?

2023-08-07 13:22 UTC, guillaumeap commented on inmoose/consensus_clustering/consensus_clustering.py
> +            ids_ = np.array(list(combinations(np.sort(np.where(prediction==0)[0]), 2))).T
prediction == clust here?
Maybe you can compute this once for each cluster instead of twice?

2023-08-07 13:33 UTC, soleneweill commented on inmoose/consensus_clustering/consensus_clustering.py
> +    def compute_bestk(self):
Is it 10 or 11 that I should put?

2023-08-07 13:35 UTC, guillaumeap commented on inmoose/consensus_clustering/consensus_clustering.py
> +    def compute_bestk(self):
10

2023-08-07 13:46 UTC, soleneweill commented on inmoose/consensus_clustering/consensus_clustering.py
> +    def compute_bestk(self):
I added it as a element of the class in the init function

2023-08-08 07:08 UTC, EpigeneMax requested changes
Mostly documentation comments.
I also realize that your "Arguments" and "Returns" underlines use extra hyphens.

You should also consider adding a section to the documentation, to explain the use cases for consensus clustering and maybe provide one or two examples.

2023-08-08 07:08 UTC, EpigeneMax commented on inmoose/consensus_clustering/consensus_clustering.py
> +import numpy as np
Add a copyright header (see other inmoose source files)

2023-08-10 14:24 UTC, guillaumeap reviewed
Very cool plots, I just have a question concerning col_colors in clustermap

2023-08-10 14:24 UTC, guillaumeap commented on inmoose/consensus_clustering/consensus_clustering.py
> +                yticklabels=False,xticklabels=False, figsize=(10,10), col_colors=col_color)
Are you sure that an array of string is enough here if we want to stack multiple data elements?
In clustermap example, it looks more like a series (or a dataframe for multiple info) @soleneweill

2023-08-10 16:57 UTC, guillaumeap approved these changes

2023-09-06 08:10 UTC, EpigeneMax approved these changes

2023-09-06 08:23 UTC, merged